# Generated by Django 5.1.4 on 2025-01-12 08:21

import ImageManagement.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ImageManagement", "0003_imagemodel_source_image_imagemodel_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="size",
        ),
        migrations.AlterField(
            model_name="imagemodel",
            name="image",
            field=models.ImageField(
                storage=ImageManagement.storage.MediaStorage(), upload_to="Images/"
            ),
        ),
    ]
