# Generated by Django 5.1.4 on 2025-01-12 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ImageManagement", "0004_remove_imagemodel_size_alter_imagemodel_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagemodel",
            name="updated_at",
        ),
    ]
