# Generated by Django 5.1.4 on 2025-01-13 17:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ImageManagement", "0005_remove_imagemodel_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Metadata",
        ),
    ]
