# Generated by Django 5.1.2 on 2024-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShortenerAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='accesscount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
