# Generated by Django 5.1.4 on 2024-12-25 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Progression", "0002_alter_scheduler_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduler",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scheduler",
            name="status",
            field=models.CharField(
                choices=[
                    ("STARTED", "Started"),
                    ("COMPLETED", "Completed"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
