# Generated by Django 5.1.6 on 2025-02-12 15:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asims_Leaderboard", "0002_remove_game_score_alter_game_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUserGameProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("wins", models.PositiveIntegerField(default=0)),
                ("losses", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user game profile",
                "verbose_name_plural": "historical user game profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="submissionhistory",
            name="game",
        ),
        migrations.AddConstraint(
            model_name="usergameprofile",
            constraint=models.UniqueConstraint(
                fields=("user", "game"), name="unique_game"
            ),
        ),
        migrations.AddField(
            model_name="historicalusergameprofile",
            name="game",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="Asims_Leaderboard.game",
            ),
        ),
        migrations.AddField(
            model_name="historicalusergameprofile",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalusergameprofile",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="SubmissionHistory",
        ),
    ]
