# Generated by Django 5.1.6 on 2025-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Asims_Leaderboard", "0003_historicalusergameprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalusergameprofile",
            name="history_user",
        ),
        migrations.AddField(
            model_name="historicalusergameprofile",
            name="history_user_id",
            field=models.IntegerField(null=True),
        ),
    ]
