# Generated by Django 5.1.3 on 2024-11-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('sender_id', models.CharField(max_length=250)),
                ('timestamp', models.DateField(auto_now_add=True, verbose_name='Timestamp: ')),
            ],
        ),
    ]
