# Generated by Django 5.1.3 on 2024-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CLI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_history',
            name='group_name',
            field=models.CharField(default=1, max_length=250),
        ),
        migrations.AlterField(
            model_name='chat_history',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp: '),
        ),
    ]
