# Generated by Django 5.1.4 on 2024-12-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Workouts", "0003_rename_workout_session_workout_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="workout_plan",
            name="name",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="exercise_session",
            unique_together={("exercise", "sets", "repetitions", "weights")},
        ),
    ]
