# Generated by Django 5.1.5 on 2025-01-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StdSeatingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat", models.CharField(max_length=50, null=True)),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("luxury class", "Luxury Class"),
                            ("midwit class", "Midwit Class"),
                            ("ghetto class", "Ghetto Class"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="moviescreening",
            name="price",
        ),
        migrations.RemoveField(
            model_name="moviescreening",
            name="seats",
        ),
        migrations.AddField(
            model_name="movie",
            name="date_released",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(to="MovieReservations.genre"),
        ),
    ]
