# Generated by Django 5.1.5 on 2025-01-28 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "MovieReservations",
            "0003_stdseatingplan_remove_moviescreening_price_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stdseatingplan",
            name="seat_type",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="cost",
        ),
        migrations.CreateModel(
            name="Seats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("luxury class", "Luxury Class"),
                            ("midwit class", "Midwit Class"),
                            ("ghetto class", "Ghetto Class"),
                        ],
                        max_length=50,
                    ),
                ),
                ("available", models.BooleanField()),
                (
                    "seat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MovieReservations.stdseatingplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="moviescreening",
            name="Seats_booked",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MovieReservations.seats",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MovieReservations.seats",
            ),
        ),
    ]
