# Generated by Django 5.1.5 on 2025-01-29 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "MovieReservations",
            "0004_remove_stdseatingplan_seat_type_remove_ticket_cost_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moviescreening",
            name="Seats_booked",
        ),
    ]
