# Generated by Django 5.1.5 on 2025-01-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0005_remove_moviescreening_seats_booked"),
    ]

    operations = [
        migrations.AddField(
            model_name="seats",
            name="movie_screening",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MovieReservations.moviescreening",
            ),
        ),
    ]
