# Generated by Django 5.1.5 on 2025-01-29 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0006_seats_movie_screening"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seats",
            old_name="seat",
            new_name="seat_loc",
        ),
    ]
