# Generated by Django 5.1.5 on 2025-01-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0007_rename_seat_seats_seat_loc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seats",
            name="seat_type",
        ),
        migrations.AddField(
            model_name="stdseatingplan",
            name="seat_type",
            field=models.CharField(
                choices=[
                    ("luxury class", "Luxury Class"),
                    ("midwit class", "Midwit Class"),
                    ("ghetto class", "Ghetto Class"),
                ],
                default="midwit class",
                max_length=50,
            ),
        ),
    ]
