# Generated by Django 5.1.5 on 2025-01-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0008_remove_seats_seat_type_stdseatingplan_seat_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stdseatingplan",
            name="seat_type",
            field=models.CharField(
                choices=[
                    ("luxury class", "Luxury Class"),
                    ("midwit class", "Midwit Class"),
                    ("ghetto class", "Ghetto Class"),
                ],
                default="midwit class",
                max_length=50,
                null=True,
            ),
        ),
    ]
