# Generated by Django 5.1.5 on 2025-01-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0009_alter_stdseatingplan_seat_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.CharField(max_length=90, null=True),
        ),
    ]
