# Generated by Django 5.1.5 on 2025-01-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0010_ticket_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="seat_loc",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MovieReservations.stdseatingplan",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MovieReservations.seats",
            ),
        ),
    ]
