# Generated by Django 5.1.5 on 2025-01-30 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0011_alter_seats_seat_loc_alter_ticket_seat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seats",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="seats",
            name="seat_loc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MovieReservations.stdseatingplan",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MovieReservations.seats",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seats",
            unique_together={("seat_loc", "movie_screening")},
        ),
    ]
