# Generated by Django 5.1.5 on 2025-02-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "MovieReservations",
            "0012_alter_seats_available_alter_seats_seat_loc_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="moviescreening",
            old_name="seats_sold",
            new_name="seats_left",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("declined", "Declined"),
                    ("used", "Used"),
                ],
                default="Valid",
                max_length=30,
            ),
        ),
    ]
