# Generated by Django 5.1.5 on 2025-02-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "MovieReservations",
            "0013_rename_seats_sold_moviescreening_seats_left_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviescreening",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("valid", "Valid"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                ],
                default="Valid",
                max_length=30,
            ),
        ),
    ]
