# Generated by Django 5.1.5 on 2025-02-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MovieReservations", "0014_alter_moviescreening_id_alter_ticket_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviescreening",
            name="valid",
            field=models.BooleanField(default=True),
        ),
    ]
