# Generated by Django 5.1.3 on 2024-12-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_session',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
