# Generated by Django 5.1.4 on 2024-12-27 09:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Progression", "0003_scheduler_user_alter_scheduler_status"),
        ("Workouts", "0002_workout_session_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Workout_Session",
            new_name="Workout_Plan",
        ),
    ]
