# Generated by Django 5.1.7 on 2025-03-24 12:51

import product_catalog_project.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_catalog_project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                max_length=900,
                null=True,
                storage=product_catalog_project.storage.MediaStorage(),
                upload_to="images/",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=20),
        ),
    ]
