# Generated by Django 5.1.4 on 2025-03-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_catalog_project", "0002_alter_product_image_alter_product_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
